---
title: "data_tidying"
output: html_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

## Clean data

```{r}
catch_original <-  read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
catch_data <- catch_original %>% 
  select(-All, -notesRegCode)
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", "1", Chinook)) %>%
  mutate(Chinook = as.integer(Chinook))
```

```{r}
i <- which(is.na(catch_clean$Chinook))
print(i)
catch_original[i,]
```

## Reahaping data
```{r}
catch_long <- catch_clean %>%
  pivot_longer(cols = c(3:7), names_to = "Species", values_to = "Catch") %>% 
  rename(catch_thousands = Catch) %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)
  
  
head(catch_long)
```

```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from =Region, values_from = catch)

head(catch_wide)
```


## Split-Apply-Combine
```{r}
mean_region <- catch_long %>% 
  filter(Species == "Sockeye") %>% 
  group_by(Region, Species) %>%
  summarise(catch_mean = mean(catch),
            n = n())

head(mean_region)
```
 

```{r}
region_defs <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))

nrow(catch_joined) == nrow(catch_long)
```


